version: '2.0'

services:
  api:
    image: linkextractor-api:v1-py
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
  web:
    image: linkextractor-web:v1-php
    build: ./www
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
  push_service:
    build: .
    image: https://hub.docker.com/repository/docker/sabsih/dockercourse:v1
  redis:
    image: redis
