version: '2'

services:
  api:
    image: linkextractor-api:v1-py
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
  web:
    image: linkextractor-web:v1-php
    build: ./www
    ports:
      - "8081:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
  push: 
    command: docker exec -it -u 0 82100e34a075
    command: docker login -u sabsih -p DC2JC34sZfTF7M3
    image: https://hub.docker.com/repository/docker/sabsih/dockercourse:ourApp
  redis:
    image: redis
